[env:esp32-c3-devkitm-1]
platform = espressif32 @ 6.6.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

board_build.flash_mode = dio
board_build.f_flash = 40000000L

upload_protocol = espota
upload_port = target1.local
upload_flags =
    --auth=Buzz987

lib_deps =
    fastled/FastLED @ ^3.6.0
    tzapu/WiFiManager @ ^2.0.17
    z3t0/IRremote @ ^4.4.1
    bblanchon/ArduinoJson @ ^7.0.0
    knolleary/PubSubClient @ ^2.8
